In [1]:
N,A,B=map(int,input().split())
print(min(N*A,B))

 4 2 7


7


In [2]:
1.0==1

True

In [ ]:
N,D=map(int,input().split())
X=[]
for n in range(N):
    X.append(list(map(int,input().split())))
count=0
for i in range(N):
    for j in range(i+1,N):
        distance=sum([(X[i][d]-X[j][d])**2 for d in range(D)])**0.5
        if distance==int(distance):
            count+=1
print(count)

In [10]:
L,R=map(int,input().split())
if R-L>=2018:
    A=list(range(2019))
else:
    A=set([n%2019 for n in range(L,R+1)])
    A=list(A)
n=len(A)
minimun=2019
for i in range(n):
    for j in range(i+1,n):
        new=(A[i]*A[j])%2019
        if new<minimun:
            minimun=new
print(minimun)

 4 5


20


In [4]:
A

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [1]:
import numpy as np
a=np.array([[1,1,0,0,0,0,0],
            [0,1,1,0,0,0,0],
            [0,0,1,1,0,0,0],
            [0,0,0,1,1,0,0],
            [0,0,0,0,1,1,0],
            [0,0,0,0,0,1,1],
            [1,0,0,0,0,0,1]])
print(a)
b=np.linalg.inv(a)
print(b)

[[1 1 0 0 0 0 0]
 [0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1]
 [1 0 0 0 0 0 1]]
[[ 0.5 -0.5  0.5 -0.5  0.5 -0.5  0.5]
 [ 0.5  0.5 -0.5  0.5 -0.5  0.5 -0.5]
 [-0.5  0.5  0.5 -0.5  0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5  0.5 -0.5  0.5 -0.5]
 [-0.5  0.5 -0.5  0.5  0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5  0.5  0.5 -0.5]
 [-0.5  0.5 -0.5  0.5 -0.5  0.5  0.5]]


In [2]:
for i in range(2**10):
    a=1

In [15]:
N=int(input())
A=[int(_) for _ in input().split()]
X=[]
x=0
for j in range(N):
    if (j%N)%2==0:
        x+=A[j]
    else:
        x-=A[j]
X.append(x)
for i in range(1,N):
    x=2*A[i-1]-X[i-1]
    X.append(x)
print(' '.join(map(str, X)))

 3
 100 100 0


0 200 0


In [4]:
print(tuple([1,2,3]))

(1, 2, 3)


In [14]:
N=10**3-1
A=[2 for n in range(N)]
X=[]
x=0
for j in range(N):
    if ((j-i)%N)%2==0:
        x+=A[j]
    else:
        x-=A[j]
X.append(x)
for i in range(1,N):
    x=2*A[i-1]-X[i-1]
    X.append(x)
print(' '.join(map(str, X)))

2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 

In [ ]:
mod=10**9+7
N,K=map(int,input().split())
graph=set()
for n in range(N-1):
    a,b=map(int,input().split())
    graph|={(a,b)}
start=1
visited=[False for n in range(N)]
candidates=[start]

while candidates!=[]:
    visiting=candidates.pop(0)
    visited[visiting]=True
    

In [18]:
a=set()
a|={2,3}

In [19]:
a

{2, 3}