In [3]:
L=list(map(int,input().split()))
L.sort()
print(L[0]+L[1])

 3 2 3


5


In [14]:
N=int(input())
W=list(map(int,input().split()))
S1=W[0]
S2=sum(W[1:N])
M=abs(S1-S2)
for i in range(1,N):
    S1+=W[i]
    S2-=W[i]
    newM=abs(S1-S2)
    if newM<M:
        M=newM
print(M)

 3
 1 2 3


0


In [ ]:
N,M=map(int,input().split())
a=[]
for m in range(M):
    a.append(int(input()))
aa=[-1]+a+[N]
b=[aa[m+1]-aa[m]-2 for m in range(M+1)]
def check(a):
    for m in range(M-1):
        if a[m+1]-a[m]==1:
            return False
    return True
def fibo(n):
    if n==0 or n==1:
        return 1
    else:
        A=[1,1]
        for i in range(2,n+1):
            A=[A[-1]]+[sum(A)]
        return A[-1]
x=1
for _ in b:
    x*=fibo(_)
print(x%1000000007)

def main():
    if check(a)==False:
        return 0
    else:
        x=1
        for _ in b:
            x*=fibo(_)
        return x
    
main()

In [19]:
def check(a):
    for m in range(M-1):
        if a[m+1]-a[m]==1:
            return False
    return True

In [22]:
M=3
a=[1,4,5]
check(a)

False

In [13]:
def fibo(n):
    if n==0 or n==1:
        return 1
    else:
        A=[1,1]
        for i in range(2,n+1):
            A=[A[-1]]+[sum(A)]
        return A[-1]

In [21]:
fibo(10**5)%1000000007

967618232

In [6]:
a=[1,23,45,67,89]
a=[-1]+a+[100]

In [7]:
a

[-1, 1, 23, 45, 67, 89, 100]

In [8]:
b=[a[m+1]-a[m]-2 for m in range(5+1)]

In [9]:
b

[0, 20, 20, 20, 20, 9]

In [4]:
fibo(6)

13

In [10]:
x=1
for _ in b:
    x*=fibo(_)
print(x%1000000007)

757876697


In [44]:
a=[3]
a=[-1]+a+[6+1]

In [45]:
a

[-1, 3, 7]

In [48]:
b=[a[m+1]-a[m]-2 for m in range(1+1)]

In [49]:
b

[2, 2]

In [50]:
fibo(2)

2

In [1]:
1+1

2

In [ ]:
mod=1000000007
N,M=map(int,input().split())
A=[]
for m in range(M):
    A.append(int(input()))

def check(A):
    for m in range(M-1):
        if A[m+1]-A[m]==1:
            return False
    return True

def fibo(n):
    if n==0 or n==1:
        return 1
    else:
        L=[1,1]
        for i in range(2,n+1):
            L=[L[-1]]+[sum(L)]
        return L[-1]

def main(A,N):
    if check(A)==False:
        return 0
    else:
        A=[0]+A+[N+1]
        B=[max(A[n+1]-A[n]-2,0) for n in range(M+1)]
        x=1
        for b in B:
            x*=fibo(b)
        return x%mod

print(main(A,N))

1


In [13]:
mod=10**9+7
N,M=map(int,input().split())
A=[int(input()) for m in range(M)]
L=[1 for n in range(N+1)]
for a in A:
    L[a]=0
Block=[0,1]
for n in range(1,N+1):
    if L[n]:
        Block=Block[1:]+[sum(Block)%mod]
    else:
        Block=Block[1:]+[0]
print(Block[-1])

 6 1
 3


[1, 1, 1, 0, 1, 1, 1]
[0, 1]
[1, 1]
[1, 2]
[2, 0]
[0, 2]
[2, 2]
4


In [48]:
import numpy as np
H,W=map(int,input().split())
S=[list(input()) for h in range(H)]
S=[[1 if s=='.' else 0 for s in S[h]] for h in range(H)]
S=np.array(S)
L=S.copy()
R=S.copy()
U=S.copy()
D=S.copy()
for w in range(1,W):
    L[:,w]=(L[:,w-1]+1)*S[:,j]
    R[:,-(1+w)]=(R[:,-w]+1)*S[:,-(1+w)]
for h in range(1,H):
    U[h,:]=(U[h-1,:]+1)*S[h,:]
    D[-(1+h),:]=(D[-h,:]+1)*S[-(1+h),:]
print(int((L+R+U+D).max())-3)

 #..#


ValueError: invalid literal for int() with base 10: '#..#'

In [50]:
H=3
S=[list(input()) for h in range(H)]
S=[[1 if s=='.' else 0 for s in S[h]] for h in range(H)]

 ..#
 #.#
 ###


In [51]:
S

[[1, 1, 0], [0, 1, 0], [0, 0, 0]]

In [38]:
import numpy as np
L=np.ones((4,3))
print(L)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [39]:
for w in range(1,3):
    L[:,w]+=L[:,w-1]
print(L)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [43]:
int(max(L.flatten()))

3

In [52]:
A=np.ones((4,3))

In [56]:
A.max()

1.0

In [54]:
A[:,2]

array([1., 1., 1., 1.])

In [55]:
A[2,:]

array([1., 1., 1.])